#! /bin/sh

sxhkd &
$HOME/.config/polybar/launch.sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor DP-1 -d 1 2 3
bspc monitor DP-3 -d 4 5 6
bspc monitor eDP-1 -d 7 8 9

bspc config border_width         4
bspc config window_gap          12

bspc config focused_border_color \#F54260
bspc config active_border_color \#C7C7C7
bspc config normal_border_color \#787878

bspc config split_ratio                   0.52
bspc config borderless_monocle            true
bspc config gapless_monocle               true
bspc config remove_disabled_monitors      true
bspc config remove_unplugged_monitors     true

bspc rule -a TelegramDesktop state=floating
bspc rule -a Pavucontrol state=floating
bspc rule -a 'Microsoft Teams - Preview' desktop='^7'

# set screens
xrandr --dpi 144 --output eDP-1 --mode 1920x1080 --pos 0x1080 --rotate normal --output DP-1 --primary --mode 3840x2160 --pos 1920x0 --rotate normal --output DP-2 --off --output DP-3 --mode 1920x1080 --pos 0x0 --rotate normal

# custom commands
focus_follows_pointer true

