#!/bin/bash

## Created By Aditya Shakya

# MENU="$(rofi -sep "|" -dmenu -i -p 'System' -location 3 -yoffset 32 -xoffset -10 -width 12 -hide-scrollbar -line-padding 4 -padding 20 -lines 4 -font "Misc Termsyn 12" <<< " Lock| Logout| Reboot| Shutdown")"
#             case "$MENU" in
#                 *Lock) i3lock -c 000000 ;;
#                 *Logout) openbox --exit;;
#                 *Reboot) systemctl reboot ;;
#                 *Shutdown) systemctl -i poweroff
#             esac

MENU="$(rofi -sep "|" -dmenu -i -p 'System'  -hide-scrollbar -line-padding 4 -padding 20 -lines 5  <<< " Lock| Logout|  Suspend| Reboot| Shutdown")"
            case "$MENU" in
                *Lock) i3lock -c 000000 ;;
                *Logout) bspc quit;;
                *Suspend) systemctl suspend ;;
                *Reboot) systemctl reboot ;;
                *Shutdown) systemctl -i poweroff
            esac
